{"uuid":"29337f2f-437f-477b-8b95-9194fd43ea6b","historyId":"45c6424263effa90681c3502810ef8ec","fullName":"io.cucumber.testng.AbstractTestNGCucumberTests.runScenario","labels":[{"name":"package","value":"testRunner.DsalgoRunner"},{"name":"testClass","value":"testRunner.DsalgoRunner"},{"name":"testMethod","value":"runScenario"},{"name":"parentSuite","value":"Default suite"},{"name":"suite","value":"Default test"},{"name":"subSuite","value":"testRunner.DsalgoRunner"},{"name":"host","value":"LAPTOP-2KQV9F30"},{"name":"thread","value":"28176@LAPTOP-2KQV9F30.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"Runs Cucumber Scenarios","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Expected alert to contain an error message, but got: NameError: name 'hello' is not defined on line 1","trace":"java.lang.AssertionError: Expected alert to contain an error message, but got: NameError: name 'hello' is not defined on line 1\r\n\tat org.junit.Assert.fail(Assert.java:89)\r\n\tat org.junit.Assert.assertTrue(Assert.java:42)\r\n\tat stepDefinitions.ArraysStep.the_user_should_see_an_name_error_message_in_alert_window(ArraysStep.java:227)\r\n\tat âœ½.The user should see an NameError message in alert window(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:36)\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"arg1","value":"\"Arrays PracticeQuestion\""},{"name":"arg0","value":"\"Verify that user receives error for invalid python code for \"Arrays in Python\" page\""}],"start":1746224197764,"stop":1746224204649}