{"uuid":"de77a9e7-6cd0-4a58-8aa4-2183ffe85964","historyId":"a0474e606295a1e3f3869d8c6f8c4585","fullName":"io.cucumber.testng.AbstractTestNGCucumberTests.runScenario","labels":[{"name":"package","value":"testRunner.DsalgoRunner"},{"name":"testClass","value":"testRunner.DsalgoRunner"},{"name":"testMethod","value":"runScenario"},{"name":"parentSuite","value":"Default suite"},{"name":"suite","value":"Default test"},{"name":"subSuite","value":"testRunner.DsalgoRunner"},{"name":"host","value":"LAPTOP-2KQV9F30"},{"name":"thread","value":"34700@LAPTOP-2KQV9F30.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"Runs Cucumber Scenarios","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Expected an error message, but got: NameError: name 'hello' is not defined on line 1","trace":"java.lang.AssertionError: Expected an error message, but got: NameError: name 'hello' is not defined on line 1\r\n\tat org.junit.Assert.fail(Assert.java:89)\r\n\tat org.junit.Assert.assertTrue(Assert.java:42)\r\n\tat stepDefinitions.StackStep.the_user_is_able_to_see_an_Nameerror_message_in_alert_window(StackStep.java:192)\r\n\tat âœ½.The user is able to see an Nameerror message in alert window(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Stack.feature:36)\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"arg1","value":"\"This feature file contain scenario for the Stack module\""},{"name":"arg0","value":"\"Verify that user receives error for invalid python code for \"Operations in Stack\" page\""}],"start":1746244511228,"stop":1746244515666}