<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="16" passed="11" failed="5" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-09T17:29:05 CDT" name="Default suite" finished-at="2025-05-09T17:31:40 CDT" duration-ms="155313">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:testRunner.DsalgoRunner@2525ff7e]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2025-05-09T17:29:05 CDT" name="Default test" finished-at="2025-05-09T17:31:40 CDT" duration-ms="155313">
      <class name="testRunner.DsalgoRunner">
        <test-method is-config="true" signature="setUpClass(org.testng.ITestContext)[pri:0, instance:testRunner.DsalgoRunner@2525ff7e]" started-at="2025-05-09T17:29:05 CDT" name="setUpClass" finished-at="2025-05-09T17:29:08 CDT" duration-ms="2773" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@78ded8c9]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:testRunner.DsalgoRunner@2525ff7e]" started-at="2025-05-09T17:29:08 CDT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-05-09T17:29:21 CDT" duration-ms="13587" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify that user receives error for invalid python code on running "Search the array" question"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Arrays PracticeQuestion"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:testRunner.DsalgoRunner@2525ff7e]" started-at="2025-05-09T17:29:21 CDT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-05-09T17:29:30 CDT" duration-ms="8400" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify that user is able to run valid python code for "Search the array" question"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Arrays PracticeQuestion"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:testRunner.DsalgoRunner@2525ff7e]" started-at="2025-05-09T17:29:30 CDT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-05-09T17:29:38 CDT" duration-ms="8513" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify that user receives error on submitting invalid python code for "Search the array" question"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Arrays PracticeQuestion"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:testRunner.DsalgoRunner@2525ff7e]" started-at="2025-05-09T17:29:38 CDT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-05-09T17:29:47 CDT" duration-ms="8847" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify that user receives Success message on submitting valid python code for "Search the array" question"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Arrays PracticeQuestion"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[BUG: Expected message 'Submission Successful' but got: 'Some Tests failed. Please review code' expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: BUG: Expected message 'Submission Successful' but got: 'Some Tests failed. Please review code' expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at stepDefinitions.ArraysStep.the_user_gets_success_message_submission_successful_in_the_console(ArraysStep.java:299)
at âœ½.The user gets success message Submission successful in the console(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:testRunner.DsalgoRunner@2525ff7e]" started-at="2025-05-09T17:29:47 CDT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-05-09T17:29:56 CDT" duration-ms="9070" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify that user receives error for invalid python code on running Search the array question"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Arrays PracticeQuestion"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:testRunner.DsalgoRunner@2525ff7e]" started-at="2025-05-09T17:29:56 CDT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-05-09T17:30:07 CDT" duration-ms="10510" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify that user is able to run valid python code for Max Consecutive Ones question"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Arrays PracticeQuestion"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:testRunner.DsalgoRunner@2525ff7e]" started-at="2025-05-09T17:30:07 CDT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-05-09T17:30:11 CDT" duration-ms="3872" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify that user receives error on submitting invalid python code for "Max Consecutive Ones" question"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Arrays PracticeQuestion"]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.NoSuchWindowException">
            <message>
              <![CDATA[no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Build info: version: '4.29.0', revision: '5fc1ec94cb'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '23.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [617c117718df0344fcf3885cce333aa4, findElement {value=//input[@value='Login'], using=xpath}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.93, chrome: {chromedriverVersion: 136.0.7103.92 (cb81a4cc5087..., userDataDir: C:\Users\chand\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:50836}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:50836/devtoo..., se:cdpVersion: 136.0.7103.93, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 617c117718df0344fcf3885cce333aa4]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchWindowException: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Build info: version: '4.29.0', revision: '5fc1ec94cb'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '23.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [617c117718df0344fcf3885cce333aa4, findElement {value=//input[@value='Login'], using=xpath}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.93, chrome: {chromedriverVersion: 136.0.7103.92 (cb81a4cc5087..., userDataDir: C:\Users\chand\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:50836}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:50836/devtoo..., se:cdpVersion: 136.0.7103.93, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 617c117718df0344fcf3885cce333aa4
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:501)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:485)
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:215)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:368)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:362)
at stepDefinitions.ArraysStep.the_user_is_in_home_page_after_sign_in(ArraysStep.java:47)
at âœ½.The User is in home page after sign in(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:5)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchWindowException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:testRunner.DsalgoRunner@2525ff7e]" started-at="2025-05-09T17:30:11 CDT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-05-09T17:30:21 CDT" duration-ms="9930" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify that user receives Success message on submitting valid python code for "Max Consecutive Ones" question"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Arrays PracticeQuestion"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:testRunner.DsalgoRunner@2525ff7e]" started-at="2025-05-09T17:30:21 CDT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-05-09T17:30:30 CDT" duration-ms="9326" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify that user receives error for invalid python code on running Find Numbers with Even Number of Digits question"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Arrays PracticeQuestion"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:testRunner.DsalgoRunner@2525ff7e]" started-at="2025-05-09T17:30:30 CDT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-05-09T17:30:39 CDT" duration-ms="8834" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify that user is able to run valid python code for Find Numbers with Even Number of Digits question"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Arrays PracticeQuestion"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:testRunner.DsalgoRunner@2525ff7e]" started-at="2025-05-09T17:30:39 CDT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-05-09T17:30:49 CDT" duration-ms="9958" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify that user receives error on submitting invalid python code for Find Numbers with Even Number of Digits question"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Arrays PracticeQuestion"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:testRunner.DsalgoRunner@2525ff7e]" started-at="2025-05-09T17:30:49 CDT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-05-09T17:30:58 CDT" duration-ms="9627" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify that user receives Success message on submitting valid python code for Find Numbers with Even Number of Digits question"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Arrays PracticeQuestion"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[BUG: Expected message 'Submission Successful' but got: 'Error occurred during submission' expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: BUG: Expected message 'Submission Successful' but got: 'Error occurred during submission' expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at stepDefinitions.ArraysStep.the_user_gets_success_message_submission_successful_in_the_console(ArraysStep.java:299)
at âœ½.The user gets success message Submission successful in the console(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:122)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:testRunner.DsalgoRunner@2525ff7e]" started-at="2025-05-09T17:30:58 CDT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-05-09T17:31:07 CDT" duration-ms="8782" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify that user receives error for invalid python code on running Squares of a Sorted Array question"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Arrays PracticeQuestion"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:testRunner.DsalgoRunner@2525ff7e]" started-at="2025-05-09T17:31:07 CDT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-05-09T17:31:16 CDT" duration-ms="8831" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify that user is able to run valid python code for Squares of a Sorted Array question"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Arrays PracticeQuestion"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:testRunner.DsalgoRunner@2525ff7e]" started-at="2025-05-09T17:31:16 CDT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-05-09T17:31:26 CDT" duration-ms="9550" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify that user receives error on submitting invalid python code for Squares of a Sorted Array question"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Arrays PracticeQuestion"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[BUG: Expected message 'Error occurred' but got: 'No tests were collected' expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: BUG: Expected message 'Error occurred' but got: 'No tests were collected' expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at stepDefinitions.ArraysStep.the_user_gets_error_message_error_occurred_during_submission_in_the_console(ArraysStep.java:280)
at âœ½.The user gets error message Error occurred during submission in the console(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:140)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:testRunner.DsalgoRunner@2525ff7e]" started-at="2025-05-09T17:31:26 CDT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-05-09T17:31:35 CDT" duration-ms="9236" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify that user receives Success message on submitting valid python code for Squares of a Sorted Array question"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Arrays PracticeQuestion"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[BUG: Expected message 'Submission Successful' but got: 'No tests were collected' expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: BUG: Expected message 'Submission Successful' but got: 'No tests were collected' expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at stepDefinitions.ArraysStep.the_user_gets_success_message_submission_successful_in_the_console(ArraysStep.java:299)
at âœ½.The user gets success message Submission successful in the console(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:146)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:testRunner.DsalgoRunner@2525ff7e]" started-at="2025-05-09T17:31:35 CDT" name="tearDownClass" finished-at="2025-05-09T17:31:40 CDT" duration-ms="5506" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- testRunner.DsalgoRunner -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
