<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="8" passed="5" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-03T01:20:02 CDT" name="Default suite" finished-at="2025-05-03T01:20:42 CDT" duration-ms="39414">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:testRunner.DsalgoRunner@48c76607]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2025-05-03T01:20:02 CDT" name="Default test" finished-at="2025-05-03T01:20:42 CDT" duration-ms="39414">
      <class name="testRunner.DsalgoRunner">
        <test-method is-config="true" signature="setUpClass(org.testng.ITestContext)[pri:0, instance:testRunner.DsalgoRunner@48c76607]" started-at="2025-05-03T01:20:03 CDT" name="setUpClass" finished-at="2025-05-03T01:20:03 CDT" duration-ms="797" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@7296fe0b]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:testRunner.DsalgoRunner@48c76607]" started-at="2025-05-03T01:20:03 CDT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-05-03T01:20:10 CDT" duration-ms="6328" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify that user receives error for invalid python code on running Find Numbers with Even Number of Digits question"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Arrays PracticeQuestion"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:testRunner.DsalgoRunner@48c76607]" started-at="2025-05-03T01:20:10 CDT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-05-03T01:20:14 CDT" duration-ms="3994" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify that user is able to run valid python code for Find Numbers with Even Number of Digits question"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Arrays PracticeQuestion"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:testRunner.DsalgoRunner@48c76607]" started-at="2025-05-03T01:20:14 CDT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-05-03T01:20:19 CDT" duration-ms="4827" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify that user receives error on submitting invalid python code for Find Numbers with Even Number of Digits question"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Arrays PracticeQuestion"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:testRunner.DsalgoRunner@48c76607]" started-at="2025-05-03T01:20:19 CDT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-05-03T01:20:23 CDT" duration-ms="4893" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify that user receives Success message on submitting valid python code for Find Numbers with Even Number of Digits question"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Arrays PracticeQuestion"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[BUG: Expected message 'Submission successful' but got: 'Error occurred during submission']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: BUG: Expected message 'Submission successful' but got: 'Error occurred during submission'
at org.junit.Assert.fail(Assert.java:89)
at stepDefinitions.ArraysStep.the_user_gets_success_message_submission_successful_in_the_console(ArraysStep.java:402)
at ✽.The user gets success message Submission successful in the console(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:129)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:testRunner.DsalgoRunner@48c76607]" started-at="2025-05-03T01:20:23 CDT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-05-03T01:20:28 CDT" duration-ms="4504" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify that user receives error for invalid python code on running Squares of a Sorted Array question"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Arrays PracticeQuestion"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:testRunner.DsalgoRunner@48c76607]" started-at="2025-05-03T01:20:28 CDT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-05-03T01:20:32 CDT" duration-ms="4212" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify that user is able to run valid python code for Squares of a Sorted Array question"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Arrays PracticeQuestion"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:testRunner.DsalgoRunner@48c76607]" started-at="2025-05-03T01:20:32 CDT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-05-03T01:20:37 CDT" duration-ms="4847" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify that user receives error on submitting invalid python code for Squares of a Sorted Array question"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Arrays PracticeQuestion"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[BUG: Expected message 'Error occurred' but got: 'No tests were collected']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: BUG: Expected message 'Error occurred' but got: 'No tests were collected'
at org.junit.Assert.fail(Assert.java:89)
at stepDefinitions.ArraysStep.the_user_gets_error_message_error_occurred_during_submission_in_the_console(ArraysStep.java:375)
at ✽.The user gets error message Error occurred during submission in the console(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:147)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:testRunner.DsalgoRunner@48c76607]" started-at="2025-05-03T01:20:37 CDT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-05-03T01:20:42 CDT" duration-ms="4825" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify that user receives Success message on submitting valid python code for Squares of a Sorted Array question"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Arrays PracticeQuestion"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[BUG: Expected message 'Submission successful' but got: 'No tests were collected']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: BUG: Expected message 'Submission successful' but got: 'No tests were collected'
at org.junit.Assert.fail(Assert.java:89)
at stepDefinitions.ArraysStep.the_user_gets_success_message_submission_successful_in_the_console(ArraysStep.java:402)
at ✽.The user gets success message Submission successful in the console(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:153)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:testRunner.DsalgoRunner@48c76607]" started-at="2025-05-03T01:20:42 CDT" name="tearDownClass" finished-at="2025-05-03T01:20:42 CDT" duration-ms="23" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- testRunner.DsalgoRunner -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
