<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-2KQV9F30" failures="8" tests="57" name="testRunner.DsalgoRunner" time="257.109" errors="0" timestamp="2025-05-03T13:50:04 CDT" skipped="0">
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.371">
    <failure message="BUG: Expected message &#039;Submission successful&#039; but got: &#039;No tests were collected&#039;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: BUG: Expected message 'Submission successful' but got: 'No tests were collected'
at org.junit.Assert.fail(Assert.java:89)
at stepDefinitions.ArraysStep.the_user_gets_success_message_submission_successful_in_the_console(ArraysStep.java:386)
at ✽.The user gets success message Submission successful in the console(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:153)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.132"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.378"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.154"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.835"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.357"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="3.816">
    <failure message="Bug: No alert displayed when clicking Run without entering code." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Bug: No alert displayed when clicking Run without entering code.
at org.junit.Assert.fail(Assert.java:89)
at stepDefinitions.ArraysStep.the_user_should_see_an_error_message_in_alert_window(ArraysStep.java:161)
at ✽.The user should see an error message in alert window(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:269)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.178"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="3.778"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.060"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="3.854"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="3.625"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="3.602"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="3.990">
    <failure message="Bug: No alert displayed when clicking Run without entering code." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Bug: No alert displayed when clicking Run without entering code.
at org.junit.Assert.fail(Assert.java:89)
at stepDefinitions.ArraysStep.the_user_should_see_an_error_message_in_alert_window(ArraysStep.java:161)
at ✽.The user should see an error message in alert window(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:222)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.311"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="3.949"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.172"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="3.729"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="3.957"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="8.895"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="3.917"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="3.744">
    <failure message="Bug: No alert displayed when clicking Run without entering code." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Bug: No alert displayed when clicking Run without entering code.
at org.junit.Assert.fail(Assert.java:89)
at stepDefinitions.ArraysStep.the_user_should_see_an_error_message_in_alert_window(ArraysStep.java:161)
at ✽.The user should see an error message in alert window(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:174)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.345"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="3.792"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="3.893"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.174"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.065"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.544"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.028"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.241"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="3.958"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="3.914">
    <failure message="Bug: No alert displayed when clicking Run without entering code." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Bug: No alert displayed when clicking Run without entering code.
at org.junit.Assert.fail(Assert.java:89)
at stepDefinitions.ArraysStep.the_user_should_see_an_error_message_in_alert_window(ArraysStep.java:161)
at ✽.The user should see an error message in alert window(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:31)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="3.420"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.198"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.038"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.165"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="3.756"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.095"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="10.636"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.461"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.626">
    <failure message="BUG: Expected message &#039;Submission successful&#039; but got: &#039;Error occurred during submission&#039;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: BUG: Expected message 'Submission successful' but got: 'Error occurred during submission'
at org.junit.Assert.fail(Assert.java:89)
at stepDefinitions.ArraysStep.the_user_gets_success_message_submission_successful_in_the_console(ArraysStep.java:386)
at ✽.The user gets success message Submission successful in the console(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:129)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="15.493">
    <failure message="BUG: Expected message &#039;Submission successful&#039; but got: &#039;Some Tests failed. Please review code&#039;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: BUG: Expected message 'Submission successful' but got: 'Some Tests failed. Please review code'
at org.junit.Assert.fail(Assert.java:89)
at stepDefinitions.ArraysStep.the_user_gets_success_message_submission_successful_in_the_console(ArraysStep.java:386)
at ✽.The user gets success message Submission successful in the console(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:81)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.059"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.454"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.408"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.384"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.232"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="3.628"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.432">
    <failure message="BUG: Expected message &#039;Error occurred&#039; but got: &#039;No tests were collected&#039;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: BUG: Expected message 'Error occurred' but got: 'No tests were collected'
at org.junit.Assert.fail(Assert.java:89)
at stepDefinitions.ArraysStep.the_user_gets_error_message_error_occurred_during_submission_in_the_console(ArraysStep.java:359)
at ✽.The user gets error message Error occurred during submission in the console(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:147)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.069"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.080"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.593"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="5.775"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.007"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="3.653"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="3.852"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="3.837"/>
</testsuite> <!-- testRunner.DsalgoRunner -->
